id: A00BDB4AA
title: 'In Praise of Mañjuśrī: Increasing Intelligence to the Full'
type: translation
pechas:
- ID6DD5595
- I9B3A7CE4
- IE1A15FB5
source_metadata:
  languages:
  - en
  - de
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:10:50.101909
  last_modified_at: 2023-01-04 13:10:50.101925
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  ID6DD5595/D47A: F732
  I9B3A7CE4/4B18: F732
  IE1A15FB5/E112: F732
